services:
  node-exporter: 
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    ports:
      - 9100:9100
      
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    privileged: true                          # This grants cAdvisor more permissions for system stats
    ports:
      - 8081:8080
    volumes:              
      - /:/rootfs:ro                          # Mount the host filesystem
      - /var/run:/var/run:rw                  # Mount the Docker socket for container monitoring
      - /sys:/sys:ro                          # Mount /sys for system stats
      - /var/lib/docker/:/var/lib/docker:ro   # Mount Docker data directory
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379